### ISSUE TITLE
Failing to connect to rtorrent

### ISSUE THREAD

**Issue by plug-it-in** [djcode/XBMC-rTorrent-Plugin#9]
Raspberry 4 pi Buster 
Kodi 18.5
rtorrent 0.9.8

rtorrent config SCPI set as locathost:5000

Kodi log entries. Show python issues would really appreciate some help

2020-01-09 19:03:06.512 T:2606801104   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xmlrpclib.Fault'>
                                            Error Contents: <Fault -506: "Method 'd.multicall' not defined">
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.program.rtorrent/default.py", line 56, in <module>
                                                loader.main()
                                              File "/home/pi/.kodi/addons/plugin.program.rtorrent/resources/lib/mode_main.py", line 12, in main
                                                dlds = g.rtc.d.multicall('main', "d.get_name=", "d.get_hash=", "d.get_completed_chunks=", "d.get_size_chunks=", "d.get_size_files=", "d.get_directory=", "d.is_active=", "d.get_complete=", "d.get_priority=", "d.is_multi_file=", "d.get_size_bytes=" )
                                              File "/home/pi/.kodi/addons/plugin.program.rtorrent/resources/lib/xmlrpc2scgi.py", line 179, in __call__
                                                return xmlrpclib.loads(xmlresp)[0][0]
                                              File "/usr/lib/python2.7/xmlrpclib.py", line 1146, in loads
                                                return u.close(), u.getmethodname()
                                              File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
                                                raise Fault(**self._stack[0])
                                            Fault: <Fault -506: "Method 'd.multicall' not defined">
                                            -->End of Python script error report<--
2020-01-09 19:03:06.538 T:2692714704   ERROR: GetDirectory - Error getting plugin://plugin.program.rtorrent/
2020-01-09 19:03:06.547 T:2972421216   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.rtorrent/) failed

**Comment by plug-it-in** [comment]
Update : It appears in rtorrent d.multicall has changed so this maybe the source of the error. I have no idea how to fix your code all I know is this line is failing 
![image](https://user-images.githubusercontent.com/17591144/72390793-7f755380-3723-11ea-83fa-26aaff20a0d6.png)

**Comment by djcode** [comment]
It looks like the old rtorrent API was finally removed in rtorrent 0.9.7.
https://github.com/rakshasa/rtorrent/wiki/RPC-Migration-0.9
I'll see if I can get the code updated to support both APIs.
It will involve changing every method call in the plugin unfortunately.
https://github.com/rakshasa/rtorrent/wiki/rTorrent-0.9-Comprehensive-Command-list-%28WIP%29

```

```

**Comment by plug-it-in** [comment]
Its such a great idea would really appreciate this working , and thanks for all your effort

**Comment by djcode** [comment]
So someone did submit a PR to fix this back in 2016, but I remember at the time the diff was hard to read and I always meant to come back to it. https://github.com/djcode/XBMC-rTorrent-Plugin/pull/8
You might be able to use this codebase to get it working while I still work on an official release.

**Comment by plug-it-in** [comment]
Hi I clones the wallys repository and directly replaced code in the 
/.kodi/addons/plugin.program.rtorrent
and it works seemingly fine

**Comment by plug-it-in** [comment]
Doesnt work 100% deleting a torrent crashed rtorrent

**Comment by djcode** [comment]
Merged #8  This problem should be resolved.
